# Generated by Django 4.2.26 on 2025-12-02 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student who submitted the review (stored even for anonymous reviews)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.student'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Write your review about the course')),
                ('points', models.IntegerField(help_text='Rating from 0 to 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='Select from predefined tags')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='reviews.course')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reviews', to='reviews.question')),
                ('student', models.ForeignKey(blank=True, help_text='Student who submitted the review (stored even for anonymous reviews)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reviews', to='reviews.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
